name: caddy-hduran
version: '0.9.4'
summary: The HTTP/2 web server with automatic HTTPS
description: |
 Caddy is a lightweight, general-purpose web server for Windows, Mac, Linux, BSD and Android. 
 It is a capable alternative to other popular and easy to use web servers. (@caddyserver on Twitter)
 The most notable features are HTTP/2, Let's Encrypt support, Virtual Hosts, TLS + SNI, and easy 
 configuration with a Caddyfile. In development, you usually put one Caddyfile with each site. 
 In production, Caddy serves HTTPS by default and manages all cryptographic assets for you.

grade: stable
confinement: strict

apps:
  caddy:
    command: bin/caddy
    plugs: [network, network-bind]
  php-fpm:
    command: start-php-fpm
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

parts:
  caddy:
    plugin: godeps
    go-importpath: github.com/mholt/caddy
    source: http://github.com/perrito666/caddy
    source-type: git
    source-tag: v0.9.4_snap
    prime:
    - bin/caddy
  config:
    plugin: dump
    source: .
  php:
    plugin: php
    source: http://us1.php.net/get/php-7.1.9.tar.gz/from/this/mirror
    source-type: tar
    install-via: prefix
    configflags:
      - --enable-fpm
      - --disable-cgi
      - --disable-phar
      - --disable-phpdbg
      - --enable-ctype
      - --enable-mbstring
      - --enable-zip
      - --with-pdo-mysql
      - --with-zlib
      - --with-gd
      - --with-curl
      - --with-bz2
      - --with-mcrypt
      - --with-mysqli
      - --enable-exif
      - --enable-intl
      - --with-jpeg-dir=/usr/lib
      - --disable-rpath
    stage-packages:
      # These are only included here until the OS snap stabilizes
      - libxml2
      - libpng16-16
    build-packages:
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg9-dev
      - libbz2-dev
      - libmcrypt-dev
    prime:
     - -sbin/
     - -etc/
    organize:
      # Put php-fpm in bin with everything else, not sbin.
      sbin/php-fpm: bin/php-fpm
